[all:children]
spines
leafs
hosts

[spines]
spine1  router_id=10.1.0.1  asn=65101
spine2  router_id=10.1.0.2  asn=65102

[leafs]
leaf1   router_id=10.2.0.1  asn=65201
leaf2   router_id=10.2.0.2  asn=65202

[hosts]
host1   router_id=10.3.0.1  asn=65301
host2   router_id=10.3.0.2  asn=65302
